CREATE TABLE IF NOT EXISTS tb_post (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(100) NOT NULL,
    content       VARCHAR(3000) NOT NULL,
    writer        VARCHAR(20)  NOT NULL,
    view_cnt      INT         NOT NULL,
    delete_yn     TINYINT     NOT NULL,
    created_date  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP           DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS tb_comment (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id       BIGINT      NOT NULL,
    content       VARCHAR(1000) NOT NULL,
    writer        VARCHAR(20)  NOT NULL,
    delete_yn     TINYINT     NOT NULL,
    created_date  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP           DEFAULT NULL,
    FOREIGN KEY (post_id) REFERENCES tb_post (id)
);

CREATE TABLE IF NOT EXISTS tb_member (
    id            BIGINT      PRIMARY KEY AUTO_INCREMENT,
    login_id      VARCHAR(255) NOT NULL UNIQUE,
    password      VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_file (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id       BIGINT      NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    save_name     VARCHAR(40) NOT NULL,
    size          INT         NOT NULL,
    delete_yn     TINYINT     NOT NULL,
    created_date  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_date  TIMESTAMP           DEFAULT NULL,
    FOREIGN KEY (post_id) REFERENCES tb_post (id)
);
