spring:
    datasource:
        jdbc-url: jdbc:h2:tcp://localhost/~/Tools/h2study/test
        username: sa
        password:
        driver-class-name: org.h2.Driver
#    hikari:
#      maximum-pool-size: 10
#      idle-timeout: 30000
#      connection-timeout: 30000

    mvc:
        pathmatch:
            matching-strategy: ant-path_matcher

# JSESSION clear
server:
    servlet:
        session:
            tracking-modes: cookie

    # change upload file size (파일당 10MB, 최대 50MB 까지)
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB
    port: 8080

mybatis:
    configuration:
        map-underscore-to-camel-case: true

file.dir: ${user.home}/study/file/

jwt:
    secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret